@startuml

    title "Domain model"

    skinparam nodesep 150

    class Task {
        name : String
        creationTimestamp : Integer
    }

    class Project {
        name : String
        color : Integer
    }

    Task "*" - "1" Project

@enduml